version: "3.7"
services:
  rust-actix-web:
    build: ./rust
    tty: true
    volumes:
      - ../../:/rust-actix-web
    ports:
      - 9999:80
  mysql:
    image: mysql:8.0.17
    ports:
      - "3399:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: dev
    volumes:
      - ./mysql/mysql-confd:/etc/mysql/conf.d
